"""
Base Agent Class - Foundation for all specialized trading agents
"""

from abc import ABC, abstractmethod
from typing import Dict, List, Any, Optional
from datetime import datetime
from dataclasses import dataclass, field
import logging


@dataclass
class AgentSignal:
    """Trading signal generated by an agent"""
    agent_name: str
    timestamp: datetime
    symbol: str
    signal_type: str  # 'buy', 'sell', 'hold', 'strong_buy', 'strong_sell'
    confidence: float  # 0.0 to 1.0
    reasoning: str
    data: Dict[str, Any] = field(default_factory=dict)
    timeframe: str = '1h'
    priority: int = 5  # 1-10, where 10 is highest
    expected_profit: Optional[float] = None
    expected_loss: Optional[float] = None

    def to_dict(self) -> Dict[str, Any]:
        return {
            'agent_name': self.agent_name,
            'timestamp': self.timestamp.isoformat(),
            'symbol': self.symbol,
            'signal_type': self.signal_type,
            'confidence': self.confidence,
            'reasoning': self.reasoning,
            'data': self.data,
            'timeframe': self.timeframe,
            'priority': self.priority,
            'expected_profit': self.expected_profit,
            'expected_loss': self.expected_loss
        }


@dataclass
class MarketAnalysis:
    """Market analysis from an agent"""
    agent_name: str
    timestamp: datetime
    symbol: str
    analysis: Dict[str, Any]
    risk_level: float  # 0.0 to 1.0
    opportunity_score: float  # 0.0 to 1.0
    timeframe: str = '1h'
    confidence: float = 0.5

    def to_dict(self) -> Dict[str, Any]:
        return {
            'agent_name': self.agent_name,
            'timestamp': self.timestamp.isoformat(),
            'symbol': self.symbol,
            'analysis': self.analysis,
            'risk_level': self.risk_level,
            'opportunity_score': self.opportunity_score,
            'timeframe': self.timeframe,
            'confidence': self.confidence
        }


class BaseAgent(ABC):
    """Base class for all specialized trading agents"""

    def __init__(self, name: str, config: Dict[str, Any]):
        self.name = name
        self.config = config
        self.logger = logging.getLogger(f"Agent.{name}")
        self.is_active = True
        self.last_analysis_time = None
        self.performance_metrics = {
            'total_signals': 0,
            'accurate_signals': 0,
            'accuracy_rate': 0.0,
            'total_profit': 0.0,
            'total_loss': 0.0,
            'win_rate': 0.0
        }
        self.expertise_areas = []
        self.confidence_factors = {}

    @abstractmethod
    async def analyze(self, market_data: Dict[str, Any]) -> MarketAnalysis:
        """
        Analyze market data and return insights

        Args:
            market_data: Dictionary containing market data including:
                - df: pandas DataFrame with OHLCV data
                - symbol: trading pair symbol
                - timeframe: timeframe of the data
                - additional context data

        Returns:
            MarketAnalysis object with agent's insights
        """
        pass

    @abstractmethod
    async def generate_signal(self, market_data: Dict[str, Any]) -> Optional[AgentSignal]:
        """
        Generate trading signal based on analysis

        Args:
            market_data: Dictionary containing market data

        Returns:
            AgentSignal if signal is generated, None otherwise
        """
        pass

    def update_performance(self, signal_id: str, was_accurate: bool,
                          profit: float = 0.0):
        """Update agent's performance metrics"""
        self.performance_metrics['total_signals'] += 1

        if was_accurate:
            self.performance_metrics['accurate_signals'] += 1
            self.performance_metrics['total_profit'] += profit
        else:
            self.performance_metrics['total_loss'] += abs(profit)

        # Update accuracy rate
        self.performance_metrics['accuracy_rate'] = (
            self.performance_metrics['accurate_signals'] /
            self.performance_metrics['total_signals']
        )

        # Update win rate
        wins = self.performance_metrics['accurate_signals']
        total = self.performance_metrics['total_signals']
        self.performance_metrics['win_rate'] = wins / total if total > 0 else 0

        self.logger.info(
            f"Performance updated - Accuracy: {self.performance_metrics['accuracy_rate']:.2%}, "
            f"Win Rate: {self.performance_metrics['win_rate']:.2%}"
        )

    def get_performance(self) -> Dict[str, float]:
        """Get agent's performance metrics"""
        return self.performance_metrics.copy()

    def set_active(self, active: bool):
        """Enable or disable agent"""
        self.is_active = active
        self.logger.info(f"Agent {self.name} {'activated' if active else 'deactivated'}")

    def get_expertise_areas(self) -> List[str]:
        """Return list of areas this agent specializes in"""
        return self.expertise_areas.copy()

    def get_confidence_factors(self) -> Dict[str, float]:
        """Return factors that affect this agent's confidence"""
        return self.confidence_factors.copy()

    def _calculate_confidence(self, factors: Dict[str, float]) -> float:
        """Calculate overall confidence based on multiple factors"""
        if not factors:
            return 0.5

        weights = {
            'data_quality': 0.2,
            'signal_strength': 0.3,
            'market_conditions': 0.2,
            'historical_accuracy': 0.3
        }

        confidence = 0.0
        total_weight = 0.0

        for factor, value in factors.items():
            weight = weights.get(factor, 0.1)
            confidence += value * weight
            total_weight += weight

        return confidence / total_weight if total_weight > 0 else 0.5

    def _get_signal_type(self, score: float) -> str:
        """Convert numerical score to signal type"""
        if score >= 0.75:
            return 'strong_buy'
        elif score >= 0.55:
            return 'buy'
        elif score <= 0.25:
            return 'strong_sell'
        elif score <= 0.45:
            return 'sell'
        else:
            return 'hold'

    def __repr__(self) -> str:
        return f"{self.__class__.__name__}(name='{self.name}', active={self.is_active})"
